# Generated by Django 3.2.7 on 2021-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('value', models.FloatField()),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
